from utils.constants import DataSetEnum

DATASET_LABELS_MAPPING = {
    DataSetEnum.Cora.value: {
        0: "Theory",
        1: "Reinforcement_Learning",
        2: "Genetic_Algorithms",
        3: "Neural_Networks",
        4: "Probabilistic_Methods",
        5: "Case_Based",
        6: "Rule_Learning",
    },
    DataSetEnum.CiteSeer.value: {
        0: "Agents",
        1: "AI",
        2: "DB",
        3: "IR",
        4: "ML",
        5: "HCI",
    },
    DataSetEnum.PubMed.value: {
        0: "Class 1",
        1: "Class 2",
        2: "Class 3",
    },
    DataSetEnum.KarateClub.value: {
        0: "Mr. Hi",
        1: "Officer",
        2: "John A",
        3: "John M",
    },
    DataSetEnum.AMAZON_COMPUTERS.value: {
        0: "Router",
        1: "Printer",
        2: "Monitor",
        3: "Speaker",
        4: "Computer",
        5: "Mouse",
        6: "Keyboard",
        7: "Headphone",
        8: "Adapter",
        9: "Microphone",
    },
    DataSetEnum.AMAZON_PHOTO.value: {
        0: "Tripod",
        1: "Lens",
        2: "Camera",
        3: "Bag",
        4: "Filter",
        5: "Case",
        6: "Battery",
        7: "Charger",
    },
    DataSetEnum.Reddit.value: {
        0: "Hockey",
        1: "nba",
        2: "leagueoflegends",
        3: "soccer",
        4: "funny",
        5: "movies",
        6: "anime",
        7: "Overwatch",
        8: "trees",
        9: "GlobalOffensive",
        10: "nfl",
        11: "AskReddit",
        12: "gameofthrones",
        13: "conspiracy",
        14: "worldnews",
        15: "wow",
        16: "europe",
        17: "canada",
        18: "Music",
        19: "baseball",
        20: "harrypotter",
        21: "MMA",
        22: "movies",
        23: "StarWars",
        24: "AskMen",
        25: "europe",
        26: "GlobalOffensive",
        27: "canada",
        28: "Overwatch",
        29: "anime",
        30: "trees",
        31: "conspiracy",
        32: "nfl",
        33: "gameofthrones",
        34: "wow",
        35: "Music",
        36: "harrypotter",
        37: "MMA",
        38: "baseball",
        39: "nba",
        40: "soccer",
    },
    DataSetEnum.AMAZON_PRODUCTS.value: {i: str(i) for i in range(1, 108)},
    DataSetEnum.Mitcham.value: {
        0: "Low",
        1: "Medium",
        2: "High",
    },
    DataSetEnum.Travel.value: {i: str(i) for i in range(1, 8)},
    DataSetEnum.NELL.value: {i: str(i) for i in range(1, 187)},
}
